name: Scan container images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'

env:
  REGISTRY: docker.io
  IMAGE_NAME: paralusio/paralus

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      # Sanity check before publishing
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0

      - name: Test all
        run: go test -v ./...

      - name: Build an image from Dockerfile
        run: |
          docker build -f "Dockerfile" -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.10.0
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Build an image from Dockerfile (paralus-init)
        run: |
          docker build -f "Dockerfile.initialize" -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-init:${{ github.sha }} .

      # skipping below binaries as they have vulnerabilities reported
      # golang-migrate tracking issue - https://github.com/golang-migrate/migrate/issues/926
      # kratos tracking - https://ory-community.slack.com/archives/C012RJ2MQ1H/p1684750686065509
      - name: Run Trivy vulnerability scanner (paralus-init)
        uses: aquasecurity/trivy-action@0.10.0
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-init:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          skip-files: '/usr/bin/kratos,/usr/bin/migrate'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Build an image from Dockerfile (kratos-sync)
        run: |
          docker build -f "Dockerfile.synchronizer" -t ${{ env.REGISTRY }}/paralusio/kratos-synchronizer:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner (kratos-sync)
        uses: aquasecurity/trivy-action@0.10.0
        with:
          image-ref: ${{ env.REGISTRY }}/paralusio/kratos-synchronizer:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'